name: 'Common cmake steps'
description: 'Encapsulate cmake composite run steps that are common for Linux and Mac'
# reference https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-composite-run-steps-action
inputs:
  conan-gcc-version: 
    description: 'A number [gcc: 5 to 10 included] [clang: 7.3, 8.0, 8.1]'
    required: true
  conan-build-types:
    description: 'Debug or Release'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install conan
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      # bash for windows https://github.com/codecov/codecov-bash
      #         curl -s https://codecov.io/bash -o codecov.bash
      #   ./codecov.bash
      run: |
        echo CMake version:
        cmake --version
        export CONAN_CMAKE_PROGRAM=`which cmake`
        pip install conan
        pip install conan_package_tools bincrafters_package_tools
        pip install -Iv cmake>=3.17
        conan user
        mkdir _build
        python build.py
      shell: bash
      env:
        CONAN_GCC_VERSIONS: ${{ inputs.conan-gcc-versions }}
        CONAN_ARCHS: x86_64
        CONAN_BUILD_TYPES: ${{ inputs.conan-build-types }}
        BUILD_SHARED: True
        CONAN_UPLOAD: http://cytosplore.lumc.nl:8081/artifactory/api/conan/conan-local
        CONAN_USERNAME: lkeb
        CONAN_REMOTE: lkebconan
        CONAN_STABLE_BRANCH_PATTERN: "release/*|master"
        CONAN_UPLOAD_ONLY_WHEN_STABLE: 1        