name: 'Common cmake steps'
description: 'Encapsulate cmake composite run steps that are common for Linux and Mac'
# reference https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-composite-run-steps-action
inputs:
  conan-gcc-version: 
    description: 'A number [gcc: 5 6 7 8 9 ] [clang: 39 40 50 60 7 8 9]'
    required: true
  conan-build-types:
    description: 'Debug or Release'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install conan
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      # bash for windows https://github.com/codecov/codecov-bash
      #         curl -s https://codecov.io/bash -o codecov.bash
      #   ./codecov.bash
      run: |
        echo CMake version:
        cmake --version
        export CONAN_CMAKE_PROGRAM=`which cmake`
        pip install conan
        pip install conan_package_tools bincrafters_package_tools
        pip install -Iv cmake>=3.17
        export CONAN_USER_HOME=/tmp/conan
        
        conan profile new action_build
        conan profile update settings.os=Linux
        conan profile update settings.os_buildr=Linux
        conan profile update settings.arch=x86_64 action_build
        conan profile update settings.arch_build=x86_64 action_build
        conan profile update settings.compiler=gcc action_build
        conan profile update settings.compiler.version=${{ inputs.conan-gcc-version }} action_build
        conan profile update settings.compiler.libcxx=libstdc++ action_build
        conan profile update settings.build_type=${{ inputs.conan-build-types }} action_build
        conan profile show action_build
        
        mkdir _build
        python build.py
      shell: bash
      env:
        CC: gcc-${{ inputs.conan-gcc-versions }}
        CXX: gcc-${{ inputs.conan-gcc-versions }}
        CONAN_BASE_PROFILE : action_build
        CONAN_GCC_VERSIONS: ${{ inputs.conan-gcc-versions }}
        CONAN_ARCHS: x86_64
        CONAN_BUILD_TYPES: ${{ inputs.conan-build-types }}
        BUILD_SHARED: True
        CONAN_UPLOAD: http://cytosplore.lumc.nl:8081/artifactory/api/conan/conan-local
        CONAN_USERNAME: lkeb
        CONAN_REMOTE: lkebconan
        CONAN_STABLE_BRANCH_PATTERN: "release/*|master"
        CONAN_UPLOAD_ONLY_WHEN_STABLE: 1        