// SPDX-License-Identifier: LGPL-3.0-or-later
// A corresponding LICENSE file is located in the root directory of this source tree
// Copyright (C) 2023 BioVault (Biomedical Visual Analytics Unit LUMC - TU Delft)

#pragma once

#include "ManiVaultGlobals.h"

#include <QString>

namespace mv::workflow
{

/**
 * @brief Options for customizing the details of a workflow result.
 */
struct CORE_EXPORT WorkflowResultDetailsOptions
{
    QString operationName;      /** "Save project", "Open project" */
    QString subjectName;        /** "Example.mv" */

    QString overrideTitle;      /** Full title override. */
    QString overrideMessage;    /** Full intro message override. */

    static QString makeWorkflowResultDetailsTitle(const WorkflowResultDetailsOptions& options, const QString& workflowName)
    {
        if (!options.overrideTitle.isEmpty())
            return options.overrideTitle;

        if (!options.operationName.isEmpty())
            return options.operationName;

        return QStringLiteral("Workflow result - %1").arg(workflowName);
    }

    static QString makeWorkflowResultDetailsMessage(const WorkflowResultDetailsOptions& options, const QString& workflowName)
    {
        if (!options.overrideMessage.isEmpty())
            return options.overrideMessage;

        if (!options.operationName.isEmpty() && !options.subjectName.isEmpty())
            return QStringLiteral("The following messages were generated while running '%1' for '%2'.").arg(options.operationName, options.subjectName);

        if (!options.operationName.isEmpty())
            return QStringLiteral("The following messages were generated while running '%1'.").arg(options.operationName);

        return QStringLiteral("The following messages were generated by workflow '%1'.").arg(workflowName);
    }
};

}