name: 'Common cmake steps'
description: 'Encapsulate cmake composite run steps that are common for Windows, Linux and Mac'
# reference https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-composite-run-steps-action
inputs:
  conan-visual-version: 
    description: 'MSVC version: 15, 16 represent msvc-2017 or msvc-2019'
    required: true
  conan-visual-runtime: 
    description: 'MD or MDd'
    required: true
  conan-build-type:
    description: 'Debug or Release'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install conan
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      # bash for windows https://github.com/codecov/codecov-bash
      #         curl -s https://codecov.io/bash -o codecov.bash
      #   ./codecov.bash
      run: |

        pip install conan
        pip install conan_package_tools bincrafters_package_tools
        pip install -Iv cmake>=3.17
        echo CMake version:
        cmake --version
        for /f "delims=" %%i in ('where cmake') do set CONAN_CMAKE_PROGRAM="%%i"
        set CONAN_USER_HOME=%cd%\_conan
        mkdir %CONAN_USER_HOME%
        conan user
        conan remote add conan-center https://conan.bintray.com
        conan remote add %CONAN_REMOTE% %CONAN_UPLOAD%
        conan profile new action_build
        conan profile update settings.os=Windows action_build
        conan profile update settings.os_build=Windows action_build
        conan profile update settings.arch=x86_64 action_build
        conan profile update settings.arch_build=x86_64 action_build
        conan profile update settings.compiler="Visual Studio" action_build
        conan profile update settings.compiler.runtime=${{ inputs.conan-visual-runtime }} action_build
        conan profile update settings.compiler.version=${{ inputs.conan-visual-version }} action_build
        conan profile update settings.build_type=${{ inputs.conan-build-type }} action_build
        conan profile update options.hdps-core:shared=True action_build
        conan profile show action_build

        mkdir _build
        conan create . hdps-core/0.1.0@lkeb/stable --remote %CONAN_REMOTE% --profile action_build
#        python build.py
      shell: cmd
      env:
        BUILD_SHARED: True
        CONAN_UPLOAD: http://cytosplore.lumc.nl:8081/artifactory/api/conan/conan-local
        CONAN_REMOTE: lkebconan
        CONAN_STABLE_BRANCH_PATTERN: "release/*|master"
        CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
