function(mv_set_version)
    
    set(VERSION_NUMERIC "${MV_VERSION_MAJOR}.${MV_VERSION_MINOR}.${MV_VERSION_PATCH}")
    set(MV_VERSION "${VERSION_NUMERIC}" PARENT_SCOPE)
    
    set(MV_VERSION_FULL "${VERSION_NUMERIC}" PARENT_SCOPE)
    set(PROJECT_VERSION_SUFFIX " " PARENT_SCOPE)

    if(NOT "${MV_VERSION_SUFFIX}" STREQUAL "")
        set(MV_VERSION_FULL "${VERSION_NUMERIC}${MV_VERSION_SUFFIX}" PARENT_SCOPE)
        set(PROJECT_VERSION_SUFFIX "${MV_VERSION_SUFFIX}" PARENT_SCOPE)
    endif()
    
endfunction()