// SPDX-License-Identifier: LGPL-3.0-or-later 
// A corresponding LICENSE file is located in the root directory of this source tree 
// Copyright (C) 2023 BioVault (Biomedical Visual Analytics Unit LUMC - TU Delft) 

#pragma once

#include "HorizontalGroupAction.h"
#include "VerticalGroupAction.h"
#include "ToggleAction.h"
#include "DecimalAction.h"
#include "IntegralAction.h"
#include "PixelSelectionAction.h"

#include "widgets/OverlayWidget.h"

#include <QVariantMap>
#include <QLabel>
#include <QTimer>

namespace mv::plugin {
    class ViewPlugin;
}

namespace mv::gui {

/**
 * View plugin sampler action class
 *
 * Provides sampling support in view plugins
 *
 * Sampling is based on either:
 * - The current selection (SamplingMode::Selection)
 *   In this mode, the view plugin updates the sample context whenever its selection changes,
 *   it calls ViewPluginSamplerAction::setSampleContext(const SampleContext& sampleContext).
 *   The sample context is a QVariantMap and depends on the type of view plugin.
 * - Focus region (circular) around the mouse cursor (SamplingMode::FocusRegion)
 *   In this mode, the ViewPluginSamplerAction::sampleContextRequested() signal is called
 *   periodically. The view plugin collects the samples in response to the signal and calls
 *   ViewPluginSamplerAction::setSampleContext(const SampleContext& sampleContext) to update
 *   the current sample context.
 *
 * When the current sample context changes, an HTML-formatted view string is generated by
 * calling the current ViewPluginSamplerAction::ViewGeneratorFunction, which is set with
 * ViewPluginSamplerAction::setViewGeneratorFunction(...). The generated view is then either:
 * - Not shown at all (ViewingMode::None)
 * - Shown in a tooltip (ViewingMode::Tooltip)
 * - Shown in a window (ViewingMode::Windowed)
 *
 * Note: ViewPluginSamplerAction::initialize(...) needs to be called for this action to work
 * properly. In addition to a pointer to a view plugin, it requires two pointers to pixel
 * selection actions:
 * - Normal pixel selection action
 * - Sampling pixel selection action (enabled when selection is idle)
 *
 * The scatter plot plugin is a good example of how this view plugin sampler can be integrated
 * into a view plugin class.
 *
 * Note: This action is developed for internal use only
 *
 * @author Thomas Kroes
 */
class CORE_EXPORT ViewPluginSamplerAction : public HorizontalGroupAction
{
    Q_OBJECT

public:

    /** Sampling modes */
    enum class SamplingMode
    {
	    Selection,      /** Sampling is based on the current selection */
        FocusRegion,    /** Sampling is based on the current focus region */
    };

    /** Viewing modes */
    enum class ViewingMode
	{
        None,       /** Do not show samples */
        Windowed,   /** Force sample scope view plugin based view */
        Tooltip     /** Force tooltip view (regardless of the size of the tooltip) */
    };

    /** Type of generated view */
    enum class GeneratedViewType
    {
        HTML,       /** HTML formatted string */
        Widget      /** Widget */
    };

    /** Context with which the tooltip is created */
    using SampleContext = QVariantMap;

    /** View generator function which is called periodically when the mouse moves in the view (should return an HTML formatted string) */
    using HtmlViewGeneratorFunction = std::function<QString(const SampleContext&)>;

    /** Widget view generator function () */
    using WidgetViewGeneratorFunction = std::function<QWidget*(const SampleContext&)>;

    /**
     * Construct with pointer to \p parent object and title
     * @param parent Pointer to parent object
     * @param title Title of the action
     * @param viewingMode Viewing mode
     */
    Q_INVOKABLE ViewPluginSamplerAction(QObject* parent, const QString& title, const ViewingMode& viewingMode = ViewingMode::None);

    /**
     * Initializes the action and enables tooltip display
     * @param viewPlugin Pointer to view plugin (may not be nullptr)
     * @param pixelSelectionAction Pointer to pixel selection action to use (may not be nullptr)
     * @param samplerPixelSelectionAction Pointer to sampler pixel selection action to use (may not be nullptr)
     */
    void initialize(plugin::ViewPlugin* viewPlugin, PixelSelectionAction* pixelSelectionAction, PixelSelectionAction* samplerPixelSelectionAction);

    /**
     * Get viewing mode
     * @return Viewing mode
     */
    ViewingMode getViewingMode() const;

    /**
     * Set viewing mode to \p viewingMode
     * @param viewingMode Viewing mode
     */
    void setViewingMode(const ViewingMode& viewingMode);

    /**
     * Get sampling mode
     * @return Sampling mode
     */
    SamplingMode getSamplingMode() const;

    /**
     * Set sampling mode to \p samplingMode
     * @param samplingMode Viewing mode
     */
    void setSamplingMode(const SamplingMode& samplingMode);

    /**
     * Whether this sampler can be viewed, three criteria must be met:
     * - ViewPluginSamplerAction._enabledAction must be checked
     * - ViewPluginSamplerAction#_viewingMode must be either Mode::Tooltip or Mode::Windowed
     * - ViewPluginSamplerAction#_viewGeneratorFunction must be valid
     * @return 
     */
    bool canView() const;

    /**
     * Get the generated view type
     * @return Generated view type
     */
    GeneratedViewType getGeneratedViewType() const;

    /**
     * Set the generated view type to \p generatedViewType
     * @param generatedViewType Generated view type
     */
    void setGeneratedViewType(const GeneratedViewType& generatedViewType);

    /**
     * Sets the HTML view generator function to \p htmlViewGeneratorFunction (automatically sets the viewing type to GeneratedViewType::HTML)
     * @param htmlViewGeneratorFunction HTML view generator function
     */
    void setHtmlViewGeneratorFunction(const HtmlViewGeneratorFunction& htmlViewGeneratorFunction);

    /**
     * Sets the widget view generator function to \p widgetViewGeneratorFunction (automatically sets the viewing type to GeneratedViewType::Widget)
     * @param widgetViewGeneratorFunction Widget view generator function
     */
    void setWidgetViewGeneratorFunction(const WidgetViewGeneratorFunction& widgetViewGeneratorFunction);

    /**
     * Get sample context
     * @return Sample variant map
     */
    SampleContext getSampleContext() const;

    /**
     * Set the sample context and flag request an update
     * @param sampleContext Sample context
     */
    void setSampleContext(const SampleContext& sampleContext);

    /**
     * Get view string
     * @return HTML formatted string
     */
    QString getViewString() const;

    /**
     * Get view widget
     * @return Pointer to view widget (maybe nullptr)
     */
    const QWidget* getViewWidget() const;

private:

    /**
     * Set view string to \p viewString
     * @param viewString HTML formatted string
     */
    void setViewString(const QString& viewString);

    /**
     * Set generated widget to \p widget
     * @param widget Pointer to generated widget
     */
    void setViewWidget(QWidget* widget);

    /** Draws the tooltip near the cursor */
    void drawToolTip();

    /** Moves the tooltip label to the cursor */
    void moveToolTipLabel();

    /**
     * Respond to \p target object events
     * @param target Object of which an event occurred
     * @param event The event that took place
     */
    bool eventFilter(QObject* target, QEvent* event) override;

    /** Updates the action read-only status based on if it can view sample information */
    void updateReadOnly();

    /**
     * Get pointer to target widget
     * @return Pointer to target widget (maybe nullptr)
     */
    QWidget* getTargetWidget() const;

    /** Creates a sample scope plugin instance and shows it on the screen */
    void openSampleWindow();

public: // Serialization

    /**
     * Load view plugin from variant
     * @param variantMap Variant representation of the view plugin
     */
    void fromVariantMap(const QVariantMap& variantMap) override;

    /**
     * Save view plugin to variant
     * @return Variant representation of the view plugin
     */
    QVariantMap toVariantMap() const override;

public: // Action getters

    ToggleAction& getEnabledAction() { return _enabledAction; }
    ToggleAction& getHighlightFocusedElementsAction() { return _highlightFocusedElementsAction; }
    ToggleAction& getRestrictNumberOfElementsAction() { return _restrictNumberOfElementsAction; }
    IntegralAction& getMaximumNumberOfElementsAction() { return _maximumNumberOfElementsAction; }
    IntegralAction& getLazyUpdateIntervalAction() { return _lazyUpdateIntervalAction; }
    OptionAction& getSamplingModeAction() { return _samplingModeAction; }
    OptionAction& getViewingModeAction() { return _viewingModeAction; }

signals:

    /**
     * Signals that the viewing mode changed from \p previousViewingMode to \p currentViewingMode
     * @param previousViewingMode Previous viewing mode
     * @param currentViewingMode Current viewing mode
     */
    void viewingModeChanged(const ViewingMode& previousViewingMode, const ViewingMode& currentViewingMode);

    /**
     * Signals that the generated view type changed from \p previousGeneratedViewType to \p currentGeneratedViewType
     * @param previousGeneratedViewType Previous generated view type
     * @param currentGeneratedViewType Current generated view type
     */
    void generatedViewTypeChanged(const GeneratedViewType& previousGeneratedViewType, const GeneratedViewType& currentGeneratedViewType);

    /**
     * Signals that the view HTML string changed from \p previousViewString to \p currentViewString
     * @param previousViewString Previous view HTML string
     * @param currentViewString Current view HTML string
     */
    void viewStringChanged(const QString& previousViewString, const QString& currentViewString);

    /**
     * Signals that the view widget changed from \p previousViewWidget to \p currentViewWidget
     * @param previousViewWidget Previous view widget
     * @param currentViewWidget Current view widget
     */
    void viewWidgetChanged(const QWidget* previousViewWidget, const QWidget* currentViewWidget);

    /** Signals that a new sample context is required */
    void sampleContextRequested();

    /**
     * Signals that the view-ability changed to \p canView
     * @param canView Current view-ability
     */
    void canViewChanged(bool canView);

private:
    plugin::ViewPlugin*             _viewPlugin;                                /** Pointer to view plugin for which to show the tooltips */
    bool                            _isInitialized;                             /** Boolean determining whether the sampler is initialized or not */
    PixelSelectionAction*           _pixelSelectionAction;                      /** Pointer to pixel selection tool to use */
    PixelSelectionAction*           _samplerPixelSelectionAction;               /** Pointer to sampler pixel selection tool to use */
    GeneratedViewType               _generatedViewType;                         /** Type of generated view */
    HtmlViewGeneratorFunction       _htmlViewGeneratorFunction;                 /** HTML view generator function which is called periodically when the mouse moves in the view (should return an HTML formatted string) */
    WidgetViewGeneratorFunction     _widgetViewGeneratorFunction;               /** Widget view generator function (the sampler action does not take ownership of the widget) */
    ToggleAction                    _enabledAction;                             /** Action to toggle computation on/off */
    ToggleAction                    _highlightFocusedElementsAction;            /** Action to toggle focus elements highlighting */
    VerticalGroupAction             _settingsAction;                            /** Additional vertical group action for settings */
    ToggleAction                    _restrictNumberOfElementsAction;            /** Action to toggle the restriction of the maximum number of elements in the focus region */
    IntegralAction                  _maximumNumberOfElementsAction;             /** Action to restrict the maximum number of elements in the focus region */
    IntegralAction                  _lazyUpdateIntervalAction;                  /** Action to control the view update timer interval */
    OptionAction                    _samplingModeAction;                        /** Action to control the sampling mode */
	OptionAction                    _viewingModeAction;                         /** Action to control the viewing mode */
    SampleContext                   _sampleContext;                             /** Context for the tooltip */
    QTimer                          _sampleContextLazyUpdateTimer;              /** Lazily (periodically) updates the sample context tooltip string */
    bool                            _sampleContextDirty;                        /** Indicates that the sample context is dirty */
    QString                         _viewString;                                /** Generated HTML-formatted view string */
    QPointer<QWidget>               _viewWidget;                                /** Pointer to the generated view widget */
    std::unique_ptr<OverlayWidget>  _toolTipOverlayWidget;                      /** Overlay widget for the tooltip */
    QLabel                          _toolTipLabel;                              /** The text label which contains the actual tooltip text */
    TriggerAction                   _openSampleScopeWindow;                     /** Opens a sample scope window */
    plugin::ViewPlugin*             _sampleScopePlugin;                         /** Pointer to sample scope plugin (maybe nullptr) */
};

}

Q_DECLARE_METATYPE(mv::gui::ViewPluginSamplerAction)

inline const auto viewPluginSamplerActionMetaTypeId = qRegisterMetaType<mv::gui::ViewPluginSamplerAction*>("mv::gui::ViewPluginSamplerAction");
