# This workflow does not contain any actual build steps 
# it dispatches other workflows to perform the actual work.
name: TestWorkflowDispatch
on: workflow_dispatch  # Trigger this manually or possibly with a chrono
jobs:
  build_core_first:
    name: Build core first
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: hdps
          repo: core
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          workflow_file_name: testbuildcore.yml
          trigger_workflow: true
          wait_workflow: true

  build_all_plugins:
    name: Build all plugins
    runs-on: ubuntu-latest
    needs: build_core_first
    steps:
    - name: Run_Scatterplot
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: hdps/Scatterplot
        event-type: test_event
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'